@startuml
class Accommodation {
}
class AccommodationBooked {
}
class AccommodationDetails {
segmentId
actorId
placeNumber
coachNumber
direction
position
configuration
passengerProfile
equipment
level
environment
gender
smoking
petsAllowed
bike
}
class AccommodationPreferences {
segmentId
allTravelersPreferences
availablePreferences
}
class AccommodationPreferenceList {
specifiedPlace
nearTo
direction
position
configuration
passengerProfile
equipment
level
environment
gender
}
class AccommodationPreferencesSelection {
}
class AccommodationShared {
{static} id
{static} classification
description
priceDetails
pricingMode
category
product
availableSlots
travelerReferences
segmentsInOverbooking
}
class AccommodationTicketed {
{static} id
classification
priceDetails
pricingMode
category
product
travelers
accommodationDetails
providerReference
}
class Account {
{static} accountId
subType
vendor
program
holder
}
class Actor {
}
class Address {
streetNumber
streetNumberSuffix
streetName
buildingName
appartmentNumber
cityName
postalCode
county
stateProvince
countryName
name
countryCode
}
class Admission {
}
class AdmissionShared {
{static} id
providerReference
travelerReferences
priceDetails
pricingMode
availableSlots
}
class AdmissionTicketed {
}
class Ancillary {
}
class AncillarySearchBody {
{static} common
searchCriteria
searchFromOrder
}
class AncillaryDetail {
actorId
mealPreference
}
class AncillarySearch {
{static} id
timeToLive
criteria
result
}
class AncillarySelected {
}
class AncillaryShared {
{static} id
{static} classification
priceDetails
pricingMode
category
tags
product
orderItemId
groupReference
location
locationType
countries
}
class AncillaryTicketed {
{static} id
providerReference
classification
priceDetails
pricingMode
category
products
travelerReferences
}
class AnonymousTraveler {
dateOfBirth
reductions
retrievedFromProfile
}
class AncillaryBooked {
}
class AncillaryPreferenceSelection {
travelerIds
mealPreference
}
class BoundOptions {
numberOfItinerariesBefore
numberOfItinerariesAfter
viaStations
incrementalChangeTime
vehicleNumbers
}
class CalendarCriteria {
{static} distributor
country
language
currency
{static} origin
{static} destination
startDate
endDate
travelers
travelClass
returnTripProducts
outwardOfferId
productCodes
}
class CalendarPrice {
travelClass
flexibilityLevel
withRestrictions
departureDate
price
}
class CalendarSearch {
{static} id
timeToLive
calendarCriteria
calendarPrices
}
class CardAndPass {
}
class CardAndPassSearch {
{static} id
timeToLive
criteria
result
}
class CardAndPassSearchBody {
searchCriteria
}
class CardAndPassShared {
{static} id
priceDetails
pricingMode
category
tags
product
countries
}
class Cart {
}
class Contact {
emailAddresses
phoneNumbers
mailingAddresses
}
class DayOverviewCriteria {
{static} distributor
country
language
currency
{static} origin
{static} destination
date
returnDate
travelers
travelClass
offersPerFlexibility
productCodes
outwardOfferId
}
class DayOverviewSearch {
{static} id
timeToLive
criteria
travelOffers
}
class Document {
{static} id
documentType
ticketFormat
mediaType
documentLink
relatedActorsIds
groupReferences
history
relatedTicketIds
active
}
class DocumentFormat {
}
class DocumentInformation {
{static} id
}
class EmailAddress {
category
{static} address
}
class ExchangeData {
}
class ExchangeOfferBasic {
}
class ExchangeOfferProposed {
}
class ExchangeOperationAmount {
refundedAmount
additionalAmount
}
class ExchangeSelection {
{static} id
creationTime
failed
groupReference
selectedTickets
repricedTickets
orderItemIds
totalRefundAmount
refundBreakdownPerMethodOfPayment
totalAdditionalAmount
overruleReason
fee
ticketTimeLimit
}
class ExchangeTravelOffer {
{static} id
itinerary
exchangeOffers
segmentsWithoutProducts
}
class ExchangeTravelOfferBasic {
{static} id
itinerary
exchangeOffers
segmentsWithoutProducts
}
class ExchangeTravelOffersSearch {
{static} id
timeToLive
criteria
travelOffers
timeRange
scrollToken
}
class ExchangeTravelSearchBody {
}
class Fee {
}
class FinancialTransaction {
{static} id
paymentRecordId
externalTransactionId
confirmationDate
orderId
paymentBreakdown
transactionType
status
}
class FormattingOptions {
formattingEmailLanguage
formattingTicketLanguage
}
class GeoCode {
latitude
longitude
}
class Holder {
Name
Address
}
class InformationMessage {
messageType
header
lead
text
startDateTime
endDateTime
}
class ItinerariesInInput {
}
class Itinerary {
}
class ItineraryBasic {
{static} id
reconstructionId
{static} origin
{static} destination
{static} departureDateTime
{static} arrivalDateTime
{static} numberOfChanges
duration
bookableStatus
mayNotBeRideable
bookableStarting
basicTransportInformation
includesANightTrain
co2Emission
ecoUrl
realDepartureDateTime
realArrivalDateTime
containsRealTimeInfo
}
class ItinerarySearchBody {
searchCriteria
itinerariesInInput
}
class ItinerarySearch {
{static} id
timeToLive
criteria
itineraries
timeRange
scrollToken
}
class JourneyOptions {
maxNumberOfChanges
outboundOptions
inboundOptions
transportType
vehicleType
vehicleCategories
carrier
withBike
}
class Location {
{static} code
name
geoCode
}
class Loyalty {
}
class LoyaltyCard {
{static} code
{static} number
expirationDate
vendorCompanyCode
}
class MethodOfPayment {
methodOfPaymentCode
notCreditable
card
bankAccount
invoice
loyalty
voucher
pointOfSale
}
class Money {
{static} amount
currency
}
class Name {
firstName
lastName
title
}
class OfferBasic {
}
class OfferProposed {
}
class OfferSelected {
}
class OfferShared {
{static} id
direction
totalPrice
flexibilityLevel
withRestrictions
accommodationCategory
accommodationPreferences
globalTravelClass
globalReservationStatus
tags
}
class Order {
}
class OrderCommonData {
{static} id
pnrRecordLocator
state
lastUpdateDateTime
creationDateTime
}
class OrderPreview {
}
class OrderItem {
{static} id
direction
totalPrice
offerGlobalTravelClass
offerAccommodationCategory
offerFlexibilityLevel
globalReservationStatus
groupReference
status
itinerary
accommodations
admissions
ancillaries
cardAndPasses
offerTags
segmentsWithoutProducts
cleanUp
cleanUpContext
}
class PaymentBreakdownAmount {
amount
refundedAmount
}
class PaymentBreakdownItem {
}
class PaymentCard {
vendorCode
startValidityDateTime
endValidityDateTime
maskedCardNumber
holder
}
class PaymentOption {
{static} id
methodOfPayment
selected
fee
total
}
class PaymentTransaction {
paymentUrl
}
class Period {
{static} startDateTime
{static} endDateTime
}
class PhoneNumber {
category
countryCallingCode
{static} number
}
class Price {
currency
total
originalTotalAndCurrency
conversionRate
totalTaxes
originalTotalTaxes
totalFees
originalTotalFees
taxes
}
class Product {
}
class ProductOptions {
travelClass
flexibilities
productCodes
productFamilies
}
class ProductShared {
code
flexibility
productCharacteristics
family
travelersRestrictions
travelPeriodRestrictions
conditions
tags
serviceProvider
appliedReductions
}
class ProductTicketed {
}
class PspOptions {
successUrl
refusedUrl
declinedUrl
exceptionUrl
language
aliasId
aliasUsage
3DSecure
customerEmail
customerName
customerId
templateName
title
}
class ReasonAfterSales {
}
class RecipientEmails {
roles
ccEmails
formattingLanguage
}
class Reduction {
reductionCards
corporateCodes
campaignCodes
nonAgeRelatedTravelerCategories
}
class ReductionCard {
{static} code
number
vendorCompanyCode
}
class Refund {
refundAmounts
refundedTickets
nonRefundableTickets
repricedTickets
financialTransactionId
}
class RefundableTickets {
ticketId
ticketValue
originalTicketValue
penalty
originalPenalty
refundedAmount
originalRefundedAmount
endOfProbationDate
}
class RefundConditions {
refundAmounts
refundableTickets
conversionRate
nonRefundableTickets
repricedTickets
}
class RefundTotalAmounts {
refundableTicketsValue
originalRefundableTicketsValue
nonRefundableTicketsValue
originalNonRefundableTicketsValue
totalRefundPenalty
originalTotalRefundPenalty
totalRepricePenalty
originalTotalRepricePenalty
totalRepriceAdditionalFareAmount
originalTotalRepriceAdditionalFareAmount
totalRefundedAmount
originalTotalRefundedAmount
refundBreakdownPerMethodOfPayment
financialTransactions
}
class SearchCriteria {
}
class SecurePaperState {
}
class Segment {
{static} id
{static} transportType
{static} departureStation
{static} departureDateTime
{static} arrivalStation
{static} arrivalDateTime
duration
vehicle
carrierCode
servicesOnBoard
co2Emission
scheduleToBeConfirmed
departureTrack
arrivalTrack
distance
stopStations
bookableStatus
bookableStarting
realDepartureDateTime
realDepartureTrack
realArrivalDateTime
realArrivalTrack
informationMessages
status
}
class ServiceOnBoard {
{static} code
}
class StationTimetable {
referenceStation
{static} timetableType
segments
}
class StopStation {
{static} station
arrivalDateTime
arrivalTrack
departureDateTime
departureTrack
borderPoint
realArrivalDateTime
realArrivalTrack
realDepartureDateTime
realDepartureTrack
entrain
detrain
}
class Tax {
}
class Ticket {
{static} id
{static} status
orderItemId
admissionIds
ancillaryIds
accommodationIds
actorIds
cardAndPasses
fees
{static} distributorTicketNumber
distributorCode
{static} providerTicketNumber
groupReference
relatedTickets
{static} issuance
refund
void
exchange
release
afterSalesConditions
}
class TicketInfo {
{static} id
status
{static} distributorTicketNumber
}
class TicketingOptions {
{static} ticketType
{static} selected
requiredInfo
fee
}
class TicketStatus {
}
class TicketTimeLimit {
effectiveTicketTimeLimit
overridden
overrideAllowed
earliestProviderTimeLimit
}
class TotalPriceInCart {
totalPrice
totalRefundedAmount
totalAdditionalAmount
}
class TravelClassLabel {
carrierCode
label
}
class Traveler {
}
class TravelerFromOrder {
{static} refActorId
reductions
}
class TravelerInInput {
travelers
actorsFromOrder
}
class TravelOffer {
{static} id
itinerary
offers
segmentsWithoutProducts
}
class TravelOfferBasic {
{static} id
itinerary
offers
segmentsWithoutProducts
}
class TravelOffersSearch {
{static} id
timeToLive
criteria
travelOffers
timeRange
scrollToken
}
class TravelOffersSearchCommonOptions {
accommodationOnly
{static} distributor
language
currency
travelersInInput
productOptions
}
class TravelSearchBody {
searchCriteria
itinerariesInInput
}
class Vehicle {
vehicleTypes
category
code
number
description
displayName
}
class Voucher {
}
class AccommodationBookedReply {
}
class AccommodationReply {
}
class AccommodationsBookedReply {
}
class AccommodationsReply {
}
class ActorReply {
}
class ActorsReply {
}
class AdmissionReply {
}
class AdmissionsReply {
}
class AncillaryBookedReply {
}
class AncillarySearchReply {
}
class AncillarySelectedReply {
}
class AncillaryIdRequest {
{static} ancillaryId
quantity
{static} actorIds
}
class AncillariesBookedReply {
}
class AncillariesSelectedReply {
}
class CalendarOverviewReply {
}
class CardAndPassSearchReply {
}
class CartReply {
}
class CommonReply {
warnings
}
class DayOverviewReply {
}
class DocumentReply {
}
class DocumentsReply {
}
class Error {
status
code
title
detail
source
}
class ErrorReply {
errors
warnings
}
class ExchangeSelectionReply {
}
class ExchangeTravelOfferReply {
}
class ExchangeTravelSearchReply {
}
class FeesReply {
}
class FinancialTransactionsReply {
}
class Idhref {
id
href
methods
}
class ItineraryReply {
}
class ItinerarySearchReply {
}
class OfferIdOptionalIds {
offerId
accommodationIds
ancillaryIds
}
class OfferReply {
}
class OfferSelectedReply {
}
class OffersSelectedReply {
}
class OrderItemReply {
}
class OrderItemsReply {
}
class OrderReply {
}
class OrderPreviewsReply {
}
class PaymentOptionReply {
}
class PaymentOptionsReply {
}
class PaymentTransactionReply {
}
class RecipientEmailsReply {
}
class RefundReply {
}
class RefundConditionsReply {
}
class StationTimetablesReply {
}
class TicketingOptionsReply {
}
class TicketReply {
}
class TicketsReply {
}
class TicketTimeLimitReply {
}
class TravelerReply {
}
class TravelersReply {
}
class TravelOfferReply {
}
class TravelSearchReply {
}
ExchangeTravelOfferBasic -- ItineraryBasic
TicketsReply o-- Ticket
AncillarySelectedReply -- AncillarySelected
RefundableTickets -- Idhref
TravelOffer o-- OfferProposed
OfferSelected *-- OfferShared
Order *-- OrderCommonData
Ticket o-- Idhref
ExchangeOfferProposed o-- Traveler
TravelerFromOrder -- RefActor
OfferSelected -- ExchangeData
AncillarySearch o-- Ancillary
RefundableTickets -- Money
Itinerary o-- InformationMessage
AccommodationTicketed o-- Traveler
Order o-- PaymentOption
ExchangeSelection o-- PaymentBreakdownItem
TravelersReply o-- Traveler
AccommodationsReply *-- CommonReply
CalendarOverviewReply *-- CommonReply
OrderItem o-- AccommodationBooked
ExchangeSelection -- OrderItem
RefundReply *-- CommonReply
Document -- RelatedActors
CardAndPassSearch -- CardAndPassSearchBody
ErrorReply o-- Error
AdmissionTicketed o-- AccommodationTicketed
PaymentBreakdownItem *-- PaymentBreakdownAmount
Document o-- Idhref
ExchangeTravelOffersSearch o-- ExchangeTravelOfferBasic
AncillaryTicketed -- Price
Ticket -- Idhref
Ticket -- Ancillary
Admission o-- Product
ExchangeTravelOffersSearch -- Period
PaymentBreakdownItem -- MethodOfPayment
AncillaryTicketed o-- ProductTicketed
Ticket o-- CardAndPass
PaymentTransactionReply *-- CommonReply
Refund -- FinancialTransaction
AncillaryShared -- Location
CalendarCriteria -- OutwardOffer
AncillarySearchReply *-- CommonReply
DayOverviewSearch -- DayOverviewCriteria
AncillaryDetail -- Actor
TravelOfferBasic o-- OfferBasic
OrderItem -- Location
ExchangeSelection -- ReasonAfterSales
OfferSelected o-- Admission
TravelerInInput o-- AnonymousTraveler
Ticket -- TicketStatus
Segment o-- ServiceOnBoard
Tax -- Money
AccommodationBookedReply -- AccommodationBooked
ProductTicketed -- Segment
OfferSelected o-- Accommodation
Segment -- Vehicle
SearchCriteria -- JourneyOptions
DocumentReply *-- CommonReply
DocumentsReply o-- Document
Document -- RelatedTicket
Location -- GeoCode
ItinerarySearchReply *-- CommonReply
Admission o-- Idhref
AncillarySearchBody -- Location
TravelOffersSearchCommonOptions -- TravelerInInput
PaymentOptionsReply o-- PaymentOption
Cart o-- OfferSelected
OfferBasic -- Money
Ticket -- Money
AncillaryIdRequest -- Ancillary
ItineraryReply *-- CommonReply
Contact o-- EmailAddress
ExchangeTravelSearchReply -- ExchangeTravelOffersSearch
ItinerarySearch o-- Itinerary
FinancialTransactionsReply o-- FinancialTransaction
CartReply -- Cart
AdmissionTicketed *-- AdmissionShared
OfferBasic *-- OfferShared
ItinerariesInInput *-- TravelOffersSearchCommonOptions
AncillariesBookedReply *-- CommonReply
Product *-- ProductShared
OrderItem o-- Admission
Tax *-- Money
RefundConditions -- RefundableTickets
AncillaryBookedReply -- AncillaryBooked
AdmissionsReply -- Admission
ActorsReply *-- CommonReply
Order o-- Fee
RefundTotalAmounts -- Money
Account -- Account
ExchangeOfferBasic *-- OfferBasic
Ancillary *-- AncillaryShared
RefundConditionsReply -- RefundConditions
CardAndPassSearch o-- CardAndPass
Contact o-- Address
Ticket -- DocumentFormat
ExchangeTravelOffer o-- ExchangeOfferProposed
OfferSelectedReply *-- CommonReply
Order -- ExchangeSelection
PspOptions -- Alias
ActorReply -- Actor
AncillariesSelectedReply o-- AncillarySelected
ExchangeData -- ReasonAfterSales
OrderItemReply -- OrderItem
TicketInfo -- TicketStatus
AccommodationPreferencesSelection *-- AccommodationPreferenceList
OfferIdOptionalIds -- Offer
PaymentTransactionReply -- PaymentTransaction
ExchangeOfferProposed *-- ExchangeOfferBasic
CartReply *-- CommonReply
ItinerarySearchBody -- JourneyOptions
TicketingOptions -- Fee
OrderPreview -- Location
TravelOffersSearch -- Period
AncillarySearchReply -- AncillarySearch
RecipientEmailsReply -- RecipientEmails
ExchangeOperationAmount -- Money
PaymentOptionsReply *-- CommonReply
ExchangeSelection -- Fee
Reduction o-- ReductionCard
DayOverviewSearch o-- TravelOfferBasic
ItinerarySearch -- ItinerarySearchBody
TravelSearchBody -- ItinerariesInInput
OfferProposed o-- Ancillary
TravelOffersSearchCommonOptions -- ProductOptions
PaymentOptionReply -- PaymentOption
AccommodationsBookedReply *-- CommonReply
Admission *-- AdmissionShared
RefundConditions -- RefundTotalAmounts
TravelerInInput o-- TravelerFromOrder
TravelOffersSearch -- TravelSearchBody
AncillaryShared -- Idhref
TravelOffersSearch o-- TravelOfferBasic
AnonymousTraveler -- Reduction
AdmissionShared -- Price
AncillaryBookedReply *-- CommonReply
Traveler o-- LoyaltyCard
Order o-- Actor
OrderItem o-- AncillaryBooked
RefundConditions -- Idhref
TicketTimeLimitReply -- TicketTimeLimit
AdmissionTicketed o-- Segment
ItineraryBasic -- Reconstruction
OfferIdOptionalIds -- Ancillary
ExchangeTravelOffer -- Itinerary
OrderReply o-- Ticket
TicketingOptionsReply o-- TicketingOptions
Traveler -- Contact
TravelOfferBasic -- Location
StationTimetable -- Location
AccommodationBookedReply *-- CommonReply
Document o-- Address
PaymentBreakdownAmount -- Money
ExchangeTravelOffersSearch -- ExchangeTravelSearchBody
TicketReply *-- CommonReply
DayOverviewCriteria -- OutwardOffer
AccommodationsBookedReply o-- AccommodationBooked
Segment -- Location
TravelOffer -- Location
Cart o-- Traveler
Fee -- Money
TravelSearchReply *-- CommonReply
MethodOfPayment -- Voucher
Segment o-- InformationMessage
Ticket -- OrderItem
ExchangeData -- Money
AncillarySelectedReply *-- CommonReply
OrderPreviewsReply o-- OrderPreview
ProductTicketed *-- ProductShared
TravelOfferBasic -- ItineraryBasic
ActorReply *-- CommonReply
DayOverviewCriteria o-- AnonymousTraveler
ExchangeSelection -- Money
AccommodationTicketed -- ProductTicketed
FinancialTransactionsReply *-- CommonReply
StationTimetablesReply o-- StationTimetable
Actor *-- Traveler
OfferProposed o-- Accommodation
AncillarySearchBody o-- AnonymousTraveler
TravelerReply *-- CommonReply
ExchangeTravelOfferBasic -- Location
OrderItem o-- CardAndPass
Address -- Name
ActorsReply o-- Actor
OrderItemReply *-- CommonReply
DocumentsReply *-- CommonReply
OfferSelectedReply -- OfferSelected
OfferReply -- OfferProposed
ExchangeTravelOfferReply -- ExchangeTravelOffer
OrderReply *-- CommonReply
FinancialTransaction -- ExternalTransaction
AccommodationReply *-- CommonReply
JourneyOptions -- BoundOptions
FinancialTransaction -- Order
Accommodation *-- AccommodationShared
AccommodationDetails -- Segment
FeesReply o-- Fee
Segment o-- StopStation
FinancialTransaction -- PaymentRecord
AncillariesBookedReply o-- AncillaryBooked
CardAndPassSearchReply -- CardAndPassSearch
TicketsReply *-- CommonReply
Document -- RecipientEmails
Refund -- Money
Ticket -- Location
RecipientEmailsReply *-- CommonReply
PaymentOption -- Money
AccommodationShared -- Product
OfferProposed o-- Admission
OrderItemsReply o-- OrderItem
RefundReply -- Refund
ExchangeSelectionReply *-- CommonReply
OfferIdOptionalIds -- Accommodation
AccommodationTicketed -- Price
OfferReply *-- CommonReply
PaymentCard -- Holder
ExchangeOfferProposed o-- Accommodation
ExchangeSelection o-- Idhref
Price -- Money
OrderItemsReply *-- CommonReply
OfferShared o-- AccommodationPreferences
TravelSearchReply -- TravelOffersSearch
ItinerarySearch -- Period
Refund -- RefundTotalAmounts
OrderReply o-- Document
CalendarPrice -- Money
Product -- TravelClassLabel
AccommodationReply -- Accommodation
Price o-- Tax
Order -- Price
Loyalty *-- Money
OfferProposed o-- Traveler
OrderItem -- Itinerary
AdmissionsReply *-- CommonReply
MethodOfPayment -- PaymentCard
AdmissionTicketed o-- ProductTicketed
AncillaryShared -- Product
AdmissionReply -- Admission
AncillaryPreferenceSelection -- Traveler
ExchangeOfferProposed o-- Ancillary
FeesReply *-- CommonReply
OfferSelected -- Idhref
TravelerReply -- Traveler
SearchCriteria *-- TravelOffersSearchCommonOptions
OfferBasic o-- TravelClassLabel
StationTimetable o-- Segment
Accommodation o-- AccommodationPreferencesSelection
OrderCommonData o-- Idhref
Ticket -- Accommodation
ItinerarySearchReply -- ItinerarySearch
ExchangeTravelOffer -- Location
Ticket -- Actor
OrderPreview *-- OrderCommonData
Order -- TicketTimeLimit
StopStation -- Location
DocumentReply -- Document
AncillarySearch -- AncillarySearchBody
ExchangeOfferProposed o-- Admission
Order o-- TicketInfo
AncillaryIdRequest -- Actor
OrderReply -- Order
Ticket -- Price
Order o-- TicketingOptions
AccommodationShared -- Price
AncillaryShared -- Price
DayOverviewReply *-- CommonReply
CardAndPassShared -- Price
Fee *-- Money
FinancialTransaction o-- PaymentBreakdownItem
OffersSelectedReply o-- OfferSelected
ExchangeData -- Idhref
CalendarSearch o-- CalendarPrice
ExchangeTravelSearchBody -- ReasonAfterSales
TicketTimeLimitReply *-- CommonReply
Traveler -- Reduction
TravelOfferReply -- TravelOffer
Account -- Holder
CardAndPassSearchReply *-- CommonReply
OfferProposed *-- OfferBasic
RefundConditionsReply *-- CommonReply
TicketingOptionsReply *-- CommonReply
ExchangeSelectionReply -- ExchangeSelection
CalendarSearch -- CalendarCriteria
CardAndPass *-- CardAndPassShared
AncillaryBooked *-- AncillaryShared
OfferBasic -- Idhref
Holder -- Address
AccommodationPreferences -- Segment
ExchangeTravelOfferReply *-- CommonReply
Order o-- DocumentInformation
ItineraryReply -- Itinerary
Traveler *-- Name
OfferSelected o-- AncillarySelected
ExchangeData *-- ExchangeOperationAmount
Refund -- Idhref
OrderPreview -- Money
TravelSearchBody -- SearchCriteria
Voucher *-- Money
AccommodationBooked *-- AccommodationShared
AncillaryShared -- OrderItem
MethodOfPayment -- Loyalty
AncillarySelected o-- AncillaryPreferenceSelection
OfferShared -- Money
DayOverviewReply -- DayOverviewSearch
CalendarOverviewReply -- CalendarSearch
AncillarySelected *-- Ancillary
StationTimetablesReply *-- CommonReply
TicketReply -- Ticket
TravelOfferReply *-- CommonReply
Cart *-- TotalPriceInCart
CommonReply o-- Error
AdmissionTicketed o-- AncillaryTicketed
TravelOffer -- Itinerary
AccommodationTicketed o-- AccommodationDetails
Ticket -- Admission
CardAndPassSearchBody o-- AnonymousTraveler
RefundTotalAmounts o-- PaymentBreakdownItem
Order o-- OrderItem
OrderItem -- Money
AccommodationDetails -- Actor
Voucher -- Period
PaymentBreakdownItem -- Idhref
PaymentOption -- MethodOfPayment
ItineraryBasic -- Location
Refund -- RefundableTickets
PaymentOptionReply *-- CommonReply
PspOptions -- Customer
AncillaryBooked o-- AncillaryDetail
Itinerary *-- ItineraryBasic
ExchangeOfferBasic -- ExchangeData
TotalPriceInCart -- Money
AncillariesSelectedReply *-- CommonReply
ExchangeTravelSearchReply *-- CommonReply
ProductShared -- Reduction
MethodOfPayment -- Account
ExchangeTravelOfferBasic o-- ExchangeOfferBasic
AdmissionReply *-- CommonReply
Itinerary o-- Segment
ExchangeTravelSearchBody *-- TravelSearchBody
CardAndPassShared -- Product
RefundTotalAmounts o-- Idhref
RefundConditions -- Money
OrderPreviewsReply *-- CommonReply
Actor o-- Idhref
OffersSelectedReply *-- CommonReply
PaymentOption -- Fee
AccommodationsReply o-- Accommodation
Order -- RecipientEmails
AccommodationBooked o-- AccommodationDetails
OfferSelected o-- CardAndPass
TravelersReply *-- CommonReply
TravelerFromOrder -- Reduction
Contact o-- PhoneNumber
@enduml
